service: ethiopia-covid-19-gateway

frameworkVersion: '>=1.1.0 <2.0.0'

provider:
  name: aws
  stage: ${opt:stage, 'dev'} # Set the default stage used. Default is dev
  region: ${opt:region, 'us-east-2'} # Overwrite the default region used. Default is us-east-1
  runtime: nodejs12.x
  environment:
    COMMUNITY_TABLE: CommunityReports
    AUTH_ISS: https://cognito-idp.${self:provider.region}.amazonaws.com/us-east-2_AGCA6XBTP
    # TRAVELERS_TABLE: TravelersReports
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.COMMUNITY_TABLE}'
        # - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TRAVELERS_TABLE}"

functions:
  auth:
    handler: handlers/auth.authorize

  create:
    handler: handlers/create.create
    events:
      - http:
          path: covid-gateway/{type}
          method: post
          authorizer: auth
          cors: true
          request:
            parameters:
              paths:
                type: true

  list:
    handler: handlers/list.list
    events:
      - http:
          path: covid-gateway/{type}
          method: get
          authorizer: auth
          cors: true
          request:
            parameters:
              paths:
                type: true

  get:
    handler: handlers/get.get
    events:
      - http:
          path: covid-gateway/{type}/{id}
          method: get
          authorizer: auth
          cors: true
          request:
            parameters:
              paths:
                type: true
                id: true

  update:
    handler: handlers/update.update
    events:
      - http:
          path: covid-gateway/{type}/{id}
          method: put
          authorizer: auth
          cors: true
          request:
            parameters:
              paths:
                type: true
                id: true

  delete:
    handler: handlers/delete.delete
    events:
      - http:
          path: covid-gateway/{type}/{id}
          method: delete
          authorizer: auth
          cors: true
          request:
            parameters:
              paths:
                type: true
                id: true

# resources:
#   Resources:
#     CommunityTable:
#       Type: 'AWS::DynamoDB::Table'
#       DeletionPolicy: Retain
#       Properties:
#         AttributeDefinitions:
#           - AttributeName: id
#             AttributeType: S
#         KeySchema:
#           - AttributeName: id
#             KeyType: HASH
#         ProvisionedThroughput:
#           ReadCapacityUnits: 1
#           WriteCapacityUnits: 1
#         TableName: ${self:provider.environment.COMMUNITY_TABLE}
    # TravelersTable:
    #   Type: "AWS::DynamoDB::Table"
    #   DeletionPolicy: Retain
    #   Properties:
    #     AttributeDefinitions:
    #       - AttributeName: id
    #         AttributeType: S
    #     KeySchema:
    #       - AttributeName: id
    #         KeyType: HASH
    #     ProvisionedThroughput:
    #       ReadCapacityUnits: 1
    #       WriteCapacityUnits: 1
    #     TableName: ${self:provider.environment.TRAVELERS_TABLE}
